version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.10.3
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"name\":\"public\", \"variables\":[]}]"
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/dispatcher:/config
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  frontend:
    image: rollvolet/frontend-crm:3.5.1
    environment:
      EMBER_AUTH_CLIENT_ID: "552ea087-fcd9-4d53-911b-19b11ff6631a"
      EMBER_AUTH_REDIRECT_URI: "https://crm.rollvolet.info/torii/redirect.html"
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  database:
    image: semtech/sparql-parser:0.0.7
    volumes:
      - ./config/authorization:/config
      - ./data/authorization:/data
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  virtuoso:
    image: redpencil/virtuoso:1.2.0-rc.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/graphs/rollvolet"
    volumes:
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
      - ./config/db/:/opt/virtuoso-scripts
      - ./data/db:/data
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  delta-notifier:
    image: semtech/mu-delta-notifier:0.4.0
    environment:
      NORMALIZE_DATETIME_IN_QUAD: "true"
    volumes:
      - ./config/delta:/config
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  migrations:
    image: semtech/mu-migrations-service:0.9.0
    environment:
      MU_SPARQL_TIMEOUT: 300
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  search:
    image: semtech/mu-search:0.10.0-beta.5
    volumes:
      - ./config/search:/config
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  elasticsearch:
    image: semtech/mu-search-elastic-backend:1.1.0
    volumes:
      - ./data/elasticsearch/:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  msal-login:
    image: rollvolet/msal-login-service:1.0.0
    environment:
      AUTH_SCOPES: "User.Read Calendars.ReadWrite.Shared Files.ReadWrite.All"
      AUTH_REFRESH_TOKENS: "true"
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  token-cache:
    image: redis:6.2.6
    volumes:
      - ./data/token-cache:/data
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  registration:
    image: semtech/mu-registration-service:2.7.3
    entrypoint: echo "Only needed for mu script"
    environment:
      USERS_GRAPH: "http://mu.semte.ch/graphs/users"
      SESSIONS_GRAPH: "http://mu.semte.ch/graphs/sessions"
    restart: "no"
    logging: *default-logging
    labels:
      - "logging=true"
  mock-login:
    image: semtech/mu-login-service:3.0.0
    environment:
      USERS_GRAPH: "http://mu.semte.ch/graphs/users"
      SESSIONS_GRAPH: "http://mu.semte.ch/graphs/sessions"
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  sequence-numbers:
    image: rollvolet/crm-sequence-numbers-service:0.1.4
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  documents:
    image: rollvolet/document-generation-service:3.1.0
    volumes:
      - ./config/templates:/templates
      - ./config/watermarks:/watermarks
      - ./data/filedrop:/share
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  cache:
    image: semtech/mu-cache:2.0.2
    links:
    - resource:backend
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  resource:
    image: semtech/mu-cl-resources:feature-handle-tries-harder
    volumes:
      - ./config/resources:/config
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  ms-files:
    image: rollvolet/ms-files-service:0.3.5
    environment:
      MS_DRIVE_ID: "my-microsoft-drive-id"
    volumes:
      - ./data/filedrop:/upload
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  ms-calendar:
    image: rollvolet/ms-calendar-service:0.5.0
    environment:
      USE_PERSONAL_CALENDAR: "false"
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  accountancy-export:
    image: rollvolet/accountancy-export-service:0.2.1
    volumes:
      - ./data/filedrop:/share
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  reporting:
    image: rollvolet/reporting-service:0.1.0
    volumes:
      - ./data/logs/frontend-errors:/share
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
