version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  documents:
    image: rollvolet/document-generation-service:0.1.0
    volumes:
      - ./config/templates:/templates
    restart: always      
    logging: *default-logging
