version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  frontend:
    image: rollvolet/crm-frontend:0.6.0
    links:
      - backend:backend
    environment:
      STATIC_FOLDERS_REGEX: ^/(assets|font|api/files)/
    restart: always
    logging: *default-logging
  backend:
    image: rollvolet/crm-api:0.7.2
    links:
      - database:database
    volumes:
      - ./config/backend/config.json:/app/config.json
      - ./data/shared:/data
    restart: always
    logging: *default-logging
  database:
    image: mcr.microsoft.com/mssql/server:2017-GA-ubuntu
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'secret'
    volumes:
      - ./data/db:/var/opt/mssql/data
      - ./data/backups:/backups
      - ./config/migrations:/migrations
    restart: always
    logging: *default-logging
