version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  frontend:
    image: rollvolet/crm-frontend:1.6.0-rc.1
    links:
      - backend:backend
    environment:
      STATIC_FOLDERS_REGEX: ^/(assets|font|api/files)/
    restart: always
    logging: *default-logging
  backend:
    image: rollvolet/crm-api:1.5.0-rc.0
    links:
      - database:database
    volumes:
      - ./config/backend/config.json:/app/config.json
      - ./logs/backend:/app/logs
      - ./data/shared:/data
    restart: always
    logging: *default-logging
  database:
    image: mcr.microsoft.com/mssql/server:2017-GA-ubuntu
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'secret'
    volumes:
      - ./data/db:/var/opt/mssql/data
      - ./logs/database:/var/opt/mssql/log
      - ./data/backups:/backups
      - ./config/migrations:/migrations
      - ./scripts/database:/scripts
    restart: always
    logging: *default-logging
  documents:
    image: rollvolet/document-generation-service:1.5.0
    volumes:
      - ./config/templates:/templates
      - ./config/watermarks:/watermarks
    restart: always
    logging: *default-logging
