version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.10.1
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"name\":\"clean\", \"variables\":[]}, {\"name\":\"public\", \"variables\":[]}]"
    restart: always
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/dispatcher:/config
    restart: always
    logging: *default-logging
  frontend:
    image: rollvolet/frontend-crm:2.7.3
    environment:
      EMBER_AUTH_CLIENT_ID: "552ea087-fcd9-4d53-911b-19b11ff6631a"
      EMBER_AUTH_REDIRECT_URI: "https://crm.rollvolet.info/torii/redirect.html"
    restart: always
    logging: *default-logging
  database:
    image: semtech/mu-authorization:0.6.0-beta.8
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/authorization:/config
    restart: always
    logging: *default-logging
  virtuoso:
    image: redpencil/virtuoso:1.2.0-rc.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/graphs/rollvolet"
    volumes:
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
      - ./config/db/:/opt/virtuoso-scripts
      - ./data/db:/data
    restart: always
    logging: *default-logging
  delta-notifier:
    image: semtech/mu-delta-notifier:0.1.0
    volumes:
      - ./config/delta:/config
    restart: always
    logging: *default-logging
  data-conversion:
    image: rollvolet/crm-data-conversion-service
    links:
      - virtuoso:database
    volumes:
      - ./data/conversion:/data
    restart: "no"
    logging: *default-logging
  migrations:
    image: semtech/mu-migrations-service:0.7.0
    environment:
      MU_SPARQL_TIMEOUT: 300
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations
    restart: always
    logging: *default-logging
  msal-login:
    image: rollvolet/msal-login-service:1.0.0
    environment:
      AUTH_SCOPES: "User.Read Calendars.ReadWrite.Shared Files.ReadWrite.All"
      AUTH_REFRESH_TOKENS: "true"
    restart: always
    logging: *default-logging
  token-cache:
    image: redis:6.2.6
    volumes:
      - ./data/token-cache:/data
    restart: always
    logging: *default-logging
  registration:
    image: semtech/mu-registration-service:2.7.3
    entrypoint: echo "Only needed for mu script"
    environment:
      USERS_GRAPH: "http://mu.semte.ch/graphs/users"
      SESSIONS_GRAPH: "http://mu.semte.ch/graphs/sessions"
    restart: "no"
    logging: *default-logging
  mock-login:
    image: semtech/mu-login-service:3.0.0
    environment:
      USERS_GRAPH: "http://mu.semte.ch/graphs/users"
      SESSIONS_GRAPH: "http://mu.semte.ch/graphs/sessions"
    restart: always
    logging: *default-logging
  documents:
    image: rollvolet/document-generation-service:2.8.2
    volumes:
      - ./config/templates:/templates
      - ./config/watermarks:/watermarks
      - ./data/filedrop:/share
    restart: always
    logging: *default-logging
  cache:
    image: semtech/mu-cache:2.0.2
    links:
    - resource:backend
    restart: always
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.22.2
    volumes:
      - ./config/resources:/config
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
    restart: always
    logging: *default-logging
  ms-files:
    image: rollvolet/ms-files-service:0.2.0
    environment:
      MS_DRIVE_ID: "my-microsoft-drive-id"
    volumes:
      - ./data/filedrop:/upload
    restart: always
    logging: *default-logging
  ms-calendar:
    image: rollvolet/ms-calendar-service:0.4.1
    environment:
      USE_PERSONAL_CALENDAR: "false"
    restart: always
    logging: *default-logging
  accountancy-export:
    image: rollvolet/accountancy-export-service
    volumes:
      - ./data/filedrop:/share
    restart: always
    logging: *default-logging
