version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.9.1
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: "[{\"name\":\"clean\", \"variables\":[]}, {\"name\":\"public\", \"variables\":[]}]"
    restart: always
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.1
    volumes:
      - ./config/dispatcher:/config
    restart: always
    logging: *default-logging
  frontend:
    image: rollvolet/frontend-crm:2.0.12
    environment:
      EMBER_AUTH_CLIENT_ID: '552ea087-fcd9-4d53-911b-19b11ff6631a'
      EMBER_AUTH_REDIRECT_URI: 'https://crm.rollvolet.info/torii/redirect.html'
    restart: always
    logging: *default-logging
  database:
    image: semtech/mu-authorization:0.6.0-beta.7
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/authorization:/config
    restart: always
    logging: *default-logging
  virtuoso:
    image: redpencil/virtuoso:1.0.0
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/graphs/rollvolet"
    volumes:
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
      - ./config/db/:/opt/virtuoso-scripts
      - ./data/db:/data
    restart: always
    logging: *default-logging
  delta-notifier:
    image: semtech/mu-delta-notifier:0.1.0
    volumes:
      - ./config/delta:/config
    restart: always
    logging: *default-logging
  data-conversion:
    image: rollvolet/crm-data-conversion-service
    links:
      - virtuoso:database
    volumes:
      - ./data/conversion:/data
    restart: "no"
    logging: *default-logging
  migrations:
    image: semtech/mu-migrations-service:0.7.0
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations
    restart: always
    logging: *default-logging
  msal-login:
    image: rollvolet/msal-login-service:0.3.1
    environment:
      AUTH_SCOPES: "User.Read Calendars.ReadWrite.Shared Files.ReadWrite.All"
      AUTH_REFRESH_TOKENS: "true"
    volumes:
      - ./data/token-cache:/cache
    restart: always
    logging: *default-logging
  monolith-backend:
    image: rollvolet/crm-api:2.1.1
    volumes:
      - ./config/backend/config.json:/app/config.json
      - ./logs/backend:/app/logs
      - ./data/files:/data
    restart: always
    logging: *default-logging
  sql-database:
    image: mcr.microsoft.com/mssql/server:2017-GA-ubuntu
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'secret'
    volumes:
      - ./data/sql-db:/var/opt/mssql/data
      - ./logs/sql-database:/var/opt/mssql/log
      - ./data/backups:/backups
      - ./config/sql-migrations:/migrations
      - ./scripts/database:/scripts
    restart: always
    logging: *default-logging
  documents:
    image: rollvolet/document-generation-service:2.2.0
    links:
      - virtuoso:database
    volumes:
      - ./config/templates:/templates
      - ./config/watermarks:/watermarks
    restart: always
    logging: *default-logging
  cache:
    image: semtech/mu-cache:2.0.2
    links:
    - resource:backend
    restart: always
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:feature-float-and-int
    volumes:
      - ./config/resources:/config
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
    restart: always
    logging: *default-logging
  ms-files:
    image: rollvolet/ms-files-service:0.1.1
    environment:
      MS_DRIVE_ID: "my-microsoft-drive-id"
    restart: always
    logging: *default-logging
