version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  frontend:
    image: rollvolet/crm-frontend:1.10.0
    links:
      - backend:backend
    environment:
      STATIC_FOLDERS_REGEX: ^/(assets|font|api/files)/
      EMBER_OAUTH_API_KEY: '552ea087-fcd9-4d53-911b-19b11ff6631a'
      EMBER_OAUTH_SCOPE: 'api://552ea087-fcd9-4d53-911b-19b11ff6631a/access_as_user offline_access'
      EMBER_OAUTH_REDIRECT_URI: 'https://crm.rollvolet.info/torii/redirect.html'
    restart: always
    logging: *default-logging
  backend:
    image: rollvolet/crm-api:1.9.0
    links:
      - database:database
    volumes:
      - ./config/backend/config.json:/app/config.json
      - ./logs/backend:/app/logs
      - ./data/files:/data
    restart: always
    logging: *default-logging
  database:
    image: mcr.microsoft.com/mssql/server:2017-GA-ubuntu
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'secret'
    volumes:
      - ./data/sql-db:/var/opt/mssql/data
      - ./logs/database:/var/opt/mssql/log
      - ./data/backups:/backups
      - ./config/migrations:/migrations
      - ./scripts/database:/scripts
    restart: always
    logging: *default-logging
  documents:
    image: rollvolet/document-generation-service:1.7.0
    volumes:
      - ./config/templates:/templates
      - ./config/watermarks:/watermarks
    restart: always
    logging: *default-logging
