SET QUOTED_IDENTIFIER ON;
GO
ALTER INDEX ALL ON TblVerzendType  REBUILD;
GO
ALTER INDEX ALL ON TblVerzending  REBUILD;
GO
ALTER INDEX ALL ON TblTracker  REBUILD;
GO
ALTER INDEX ALL ON TblToegang  REBUILD;
GO
ALTER INDEX ALL ON TblTelVolgorde  REBUILD;
GO
ALTER INDEX ALL ON TblTelType  REBUILD;
GO
ALTER INDEX ALL ON tblTel  REBUILD;
GO
ALTER INDEX ALL ON TblTeksten  REBUILD;
GO
ALTER INDEX ALL ON TblTaal  REBUILD;
GO
ALTER INDEX ALL ON TblProdukt  REBUILD;
GO
ALTER INDEX ALL ON TblPostCode  REBUILD;
GO
ALTER INDEX ALL ON TblPloeg  REBUILD;
GO
ALTER INDEX ALL ON TblPersoneel  REBUILD;
GO
ALTER INDEX ALL ON TblParameters  REBUILD;
GO
ALTER INDEX ALL ON TblOpdracht  REBUILD;
GO
ALTER INDEX ALL ON tblOfferte  REBUILD;
GO
ALTER INDEX ALL ON TblLand  REBUILD;
GO
ALTER INDEX ALL ON TblKeyWord  REBUILD;
GO
ALTER INDEX ALL ON TblFactuurExtra  REBUILD;
GO
ALTER INDEX ALL ON TblFactuur  REBUILD;
GO
ALTER INDEX ALL ON TblDataMemo  REBUILD;
GO
ALTER INDEX ALL ON TblDataKeyWord  REBUILD;
GO
ALTER INDEX ALL ON tblData  REBUILD;
GO
ALTER INDEX ALL ON TblBtw  REBUILD;
GO
ALTER INDEX ALL ON TblBrief  REBUILD;
GO
ALTER INDEX ALL ON TblBoeking  REBUILD;
GO
ALTER INDEX ALL ON TblBezoek  REBUILD;
GO
ALTER INDEX ALL ON TblInvoiceline  REBUILD;
GO
ALTER INDEX ALL ON TblBetaaltermijn  REBUILD;
GO
ALTER INDEX ALL ON TblAanvraagX  REBUILD;
GO
ALTER INDEX ALL ON TblAanspreektitel  REBUILD;
GO
ALTER INDEX ALL ON TblAanmelding  REBUILD;
GO
ALTER INDEX ALL ON TblAanmaningTemp  REBUILD;
GO
ALTER INDEX ALL ON TblAanmaningExclude  REBUILD;
GO
ALTER INDEX ALL ON TblAanvraag  REBUILD;
GO
ALTER INDEX ALL ON TblAanmaning  REBUILD;
GO
ALTER INDEX ALL ON tblWerkUren  REBUILD;
GO
ALTER INDEX ALL ON TblIntervention  REBUILD;
GO
ALTER INDEX ALL ON TblInterventionTechnician  REBUILD;
GO
ALTER INDEX ALL ON TblOfferline  REBUILD;
GO
ALTER INDEX ALL ON TblProductUnit  REBUILD;
GO
ALTER INDEX ALL ON TblVoorschotFactuur  REBUILD;
GO
ALTER INDEX ALL ON TblVoorschot  REBUILD;
GO
ALTER INDEX ALL ON TblPlanningEvent  REBUILD;
GO
SET QUOTED_IDENTIFIER OFF;
GO
