PREFIX foaf: <http://xmlns.com/foaf/0.1/>
DELETE {
  GRAPH ?g {
    ?person foaf:member ?userGroup .
  }
} 
INSERT {
  GRAPH ?g {
    ?userGroup foaf:member ?person .
  }
} 
WHERE {
  GRAPH ?g {
    ?userGroup a foaf:Group .
    ?person foaf:member ?userGroup .
  }
}