PREFIX crm: <http://data.rollvolet.be/vocabularies/crm/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX ncal: <http://www.semanticdesktop.org/ontologies/2007/04/02/ncal#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX p2poDocument: <https://purl.org/p2p-o/document#>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/rollvolet> {
    ?order ext:indicativePlanningDate ?date ;
      ext:indicativePlanningPeriod ?period .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/rollvolet> {
    ?event a ncal:Event ;
      dct:subject ?order ;
      ncal:date ?date ;
      ncal:summary ?subject .
    ?order a p2poDocument:PurchaseOrder .

    BIND(STRBEFORE(?subject, "|") as ?period)
  }
}
