PREFIX schema: <http://schema.org/>

DELETE {
  GRAPH ?g {
    <http://data.rollvolet.be/vat-rates/79b5aafb-d4da-49c4-a631-665f2dda807f> schema:name ?name .
  }
} INSERT {
  GRAPH ?g {
    <http://data.rollvolet.be/vat-rates/79b5aafb-d4da-49c4-a631-665f2dda807f> schema:name "BTW verlegd" .
  }
} WHERE {
  GRAPH ?g {
    <http://data.rollvolet.be/vat-rates/79b5aafb-d4da-49c4-a631-665f2dda807f> schema:name ?name .
  }
}
